#!/usr/bin/env bash
#simple Shellscript for i3blocks on Pinebook pro
#05012020 geri123@gmx.net Gerhard S.
#battery-symbols: on Manjaro you need the awesome-terminal-fonts package installed!
PERCENT=$(cat /sys/class/power_supply/BAT1/capacity)
STATUS=$(cat /sys/class/power_supply/BAT1/status)
ST=""
r='\033[0;31m'
n='\033[0m'
if [ "$STATUS" = "Discharging" ]; then ST="";fi
case $((
 $PERCENT >= 0 && $PERCENT <= 5 ? 0 :
 $PERCENT > 5 && $PERCENT <= 25 ? 1 :
 $PERCENT > 25 && $PERCENT <= 50 ? 2 :
 $PERCENT > 50 && $PERCENT <= 75 ? 3 :
 $PERCENT > 75 && $PERCENT <= 100 ? 4 : 5)) in
#

       (0) echo $ST" !" $PERCENT% &&  dunstify --action="replyAction,reply" "Batería Baja";;
       (1) echo $ST" " $PERCENT%;;
       (2) echo $ST" " $PERCENT%;;
       (3) echo $ST" " $PERCENT%;;
       (4) echo $ST" " $PERCENT%;;
esac
