#!/usr/bin/env bash
#simple Shellscript for i3blocks on Pinebook pro
#05012020 geri123@gmx.net Gerhard S.
#battery-symbols: on Manjaro you need the awesome-terminal-fonts package installed!
PERCENT=$(cat /sys/class/power_supply/BAT1/capacity)
STATUS=$(cat /sys/class/power_supply/BAT1/status)
ST=""
if [ "$STATUS" = "Discharging" ]; then ST="";fi
case $((
 $PERCENT >= 0 && $PERCENT <= 5 ? 1 :
 $PERCENT > 5 && $PERCENT <= 10 ? 2 :
 $PERCENT > 10 && $PERCENT <= 25 ? 3 :
 $PERCENT > 25 && $PERCENT <= 50 ? 4 :
 $PERCENT > 50 && $PERCENT <= 75 ? 5 :
 $PERCENT > 75 && $PERCENT <= 100 ? 6 : 7 )) in
#

       (1) echo $ST" !" $PERCENT% && notify-send -u critical "Conectar Cargador";;
       (2) echo $ST" " $PERCENT% && notify-send -u low "Batería Baja";;
       (3) echo $ST" " $PERCENT%;;
       (4) echo $ST" " $PERCENT%;;
       (5) echo $ST" " $PERCENT%;;
       (6) echo $ST" " $PERCENT%;;
esac
